export const THICKNESS_MAX = 10;
export const OPACITY_MAX = 100;
export const FONT_SIZE_MAX = 100;
export const WIDTH_MAX = 1000;
export const HEIGHT_MAX = 500;
export const BORDER_TYPES = [
  { label: 'solid', selected: false },
  { label: 'dotted', selected: false },
  { label: 'dashed', selected: false },
  { label: 'double', selected: false },
  { label: 'groove', selected: false },
  { label: 'ridge', selected: false },
  { label: 'inset', selected: false },
  { label: 'outset', selected: false },
  { label: 'none', selected: false }
];
export const TEXT_ALIGN_TYPES = [
  { label: 'initial', selected: false },
  { label: 'left', selected: false },
  { label: 'right', selected: false },
  { label: 'center', selected: false },
  { label: 'justify', selected: false }
];
export const TRANSITION_TIMING_FUNCTION = [
  { label: 'ease', selected: false },
  { label: 'linear', selected: false },
  { label: 'ease-in', selected: false },
  { label: 'ease-out', selected: false },
  { label: 'ease-in-out', selected: false }
];
export const ALL_CSS = {
  borderThickness: '',
  borderStyle: '',
  borderColor: '',
  outlineThickness: '',
  outlineStyle: '',
  outlineColor: '',
  outlineOffset: '',
  borderRadius: '',
  topLeftRadius: '',
  topRightRadius: '',
  bottomRightRadius: '',
  bottomLeftRadius: '',
  horizontalBoxShadow: '',
  verticalBoxShadow: '',
  blurRadiusBoxShadow: '',
  spreadBoxShadow: '',
  colorBoxShadow: '',
  backgroundColor: '',
  backgroundColorOpacity: '',
  fontColor: '',
  fontSize: '',
  textAlign: '',
  horizontalTextShadow: '',
  verticalTextShadow: '',
  blurRadiusTextShadow: '',
  colorTextShadow: '',
  blur: '',
  brightness: '',
  contrast: '',
  grayscale: '',
  hueRotate: '',
  invert: '',
  filterOpacity: '',
  saturate: '',
  sepia: '',
  backdropBlur: '',
  backdropBrightness: '',
  backdropContrast: '',
  backdropGrayscale: '',
  backdropHueRotate: '',
  backdropInvert: '',
  backdropFilter: '',
  backdropSaturate: '',
  backdropSepia: '',
  rotateX: '',
  rotateY: '',
  rotateZ: '',
  translateX: '',
  translateY: '',
  scaleX: '',
  scaleY: '',
  skewX: '',
  skewY: '',
  transition: '',
  margin: '',
  marginTop: '',
  marginRight: '',
  marginBottom: '',
  marginLeft: '',
  padding: '',
  paddingTop: '',
  paddingRight: '',
  paddingBottom: '',
  paddingLeft: '',
  width: '',
  height: ''
};
