export const ICON_TYPES = {
  BLOCK: 'block',
  CALCULATOR: 'calculator',
  CALENDAR: 'calendar',
  CALENDAR_AND_CLOCK: 'calendar-clock',
  CHECKMARK: 'checkmark',
  CODE: 'code',
  COPY: 'copy',
  CLIPBOARD: 'clipboard',
  CLOCK: 'clock',
  CLOSE: 'close',
  DOWN_ARROW: 'down-arrow',
  DOWN_CARET: 'down-caret',
  EDIT: 'edit',
  EYE: 'eye',
  FILE: 'file',
  FLASK: 'flask',
  HOME: 'home',
  IMAGE: 'image',
  LEFT_CARET: 'left-caret',
  LEFT_ARROW: 'left-arrow',
  MINUS: 'minus',
  MUTE: 'mute',
  NO_EYE: 'no-eye',
  PAUSE: 'pause',
  PLAY: 'play',
  PLUS: 'plus',
  RIGHT_ARROW: 'right-arrow',
  RIGHT_CARET: 'right-caret',
  SAVE: 'save',
  SEARCH: 'search',
  SETTINGS: 'settings',
  SOUND: 'sound',
  TOGGLE_ON: 'toggle-on',
  TOGGLE_OFF: 'toggle-off',
  TRASH: 'trash',
  TRIPLE_BAR: 'triple-bar',
  TRIPLE_CIRCLE: 'triple-circle',
  UNDO: 'undo',
  UP_ARROW: 'up-arrow',
  UP_CARET: 'up-caret'
};

export const ICON_SIZES = {
  EXTRA_SMALL: 'xs',
  SMALL: 's',
  MEDIUM: 'm',
  LARGE: 'l',
  EXTRA_LARGE: 'xl'
};