export { ArchiveSVG } from './ArchiveSVG';
export { ArrowSVG } from './ArrowSVG';
export { ClipboardSVG } from './ClipboardSVG';
export { CloseSVG } from './CloseSVG';
export { CopyFileSVG } from './CopyFileSVG';
export { DirectorySVG } from './DirectorySVG';
export { EyeSVG } from './EyeSVG';
export { FileSVG } from './FileSVG';
export { FlaskSVG } from './FlaskSVG';
export { HomeSVG } from './HomeSVG';
export { InfoSVG } from './InfoSVG';
export { LinkSVG } from './LinkSVG';
export { PenSVG } from './PenSVG';
export { PlaySVG } from './PlaySVG';
export { PlusOrMinusSVG } from './PlusOrMinusSVG';
export { SaveSVG } from './SaveSVG';
export { SettingSVG } from './SettingSVG';
export { StarSVG } from './StarSVG';
export { TextSVG } from './TextSVG';
export { TrashSVG } from './TrashSVG';
export { TripleBarSVG } from './TripleBarSVG';
import './icon.css';
import './svg.css';
