export { default as ArrowIcon } from './ArrowIcon';
export { default as CopyIcon } from './CopyIcon';
export { default as CloseIcon } from './CloseIcon';
export { default as EditIcon } from './EditIcon';
export { default as InfoIcon } from './InfoIcon';
export { default as MinusIcon } from './MinusIcon';
export { default as PlusIcon } from './PlusIcon';
export { default as SaveIcon } from './SaveIcon';
export { default as TrashIcon } from './TrashIcon';
export { default as TripleBarIcon } from './TripleBarIcon';
export { default as UndoIcon } from './UndoIcon';
import './icon.css';